# Generated by Django 5.2 on 2025-04-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Disponible'), (0, 'No disponible')])),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sistema.usuario')),
                ('salario', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
            bases=('app_sistema.usuario',),
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sistema.usuario')),
                ('pasaporte', models.CharField(max_length=10, unique=True)),
            ],
            bases=('app_sistema.usuario',),
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sistema.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('capacidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_embarque', models.TimeField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_destino', to='app_sistema.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_origen', to='app_sistema.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sistema.empleado')),
            ],
            bases=('app_sistema.empleado',),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('checkin', 'Check-In'), ('cancelado', 'Cancelado')], max_length=10)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sistema.vuelo')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app_sistema.pasajero')),
            ],
        ),
    ]
