# Generated by Django 5.2 on 2025-06-17 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(0, 'no disponible'), (1, 'disponible')])),
                ('rol', models.CharField(choices=[('PASAJERO', 'Pasajero'), ('EMPLEADO', 'Empleado'), ('ADMIN', 'Administrador')], default='PASAJERO', max_length=20)),
                ('pasaporte', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('origen', models.CharField(max_length=50, unique=True)),
                ('destino', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_embarque', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sistema.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('checkin', 'Check-In'), ('cancelado', 'Cancelado')], max_length=10)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app_sistema.usuario')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sistema.vuelo')),
            ],
        ),
    ]
