# Generated by Django 5.2 on 2025-06-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0002_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
