# Generated by Django 5.2 on 2025-06-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0003_remove_usuario_apellido_remove_usuario_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
