# Generated by Django 5.2 on 2025-06-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0004_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.CharField(max_length=50),
        ),
    ]
