# Generated by Django 5.2 on 2025-07-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0005_alter_vuelo_destino_alter_vuelo_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('salario', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
