# Generated by Django 5.2 on 2025-07-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0006_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='codigo',
        ),
    ]
